### ISSUE TITLE
ModuleLoader.loadResourceMap is not a function

### ISSUE THREAD

**Issue by joaomilho** [jsdf/jest-alias-module-loader#1]
I suppose it's not compatible w/ jest 0.8.2. Can you confirm?

```
TypeError: ModuleLoader.loadResourceMap is not a function
    at TestRunner._getModuleLoaderResourceMap (.../node_modules/jest-cli/src/TestRunner.js:116:24)
    at TestRunner.promiseTestPathsMatching (.../node_modules/jest-cli/src/TestRunner.js:185:17)
    at findMatchingTestPaths (.../node_modules/jest-cli/src/jest.js:191:21)
    at .../node_modules/jest-cli/src/jest.js:217:9
```

**Comment by jsdf** [comment]
I believe jest now has built in support for module aliases so you probably don't need this module anymore
